### ISSUE TITLE
Trouble using load_db.py --dry_run option

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/pserv#13]
Admittedly this was my first attempt to use the load_db.py script, however I ran into a problem trying to use the --dry_run parameter.  I was using the Twinkles Run3 First40 data in: /global/cscratch1/sd/desc/twinkles/work/4/output
Later I was able to run the ingest after I gave up trying to use the --dry_run to test things out.  Was I doing something wrong? Or were my expectations about "dry_run" inappropriate?
```heatherk@cori07:/global/cscratch1/sd/desc/twinkles/work/4> load_db.py --dry_run output "Twinkles Run 3 Test"                                                        
Ingest registry file /global/cscratch1/sd/desc/twinkles/work/4/output/_parent/registry.sqlite3                                                                      
Ingest calexp info
Ingest object catalog output/deepCoadd-results/merged/0/0,0/ref-0-0,0.fits
Processing band u for 0 visits.
Processing band g for 10 visits.
Processing v250-fg R2,2 S1,1
Traceback (most recent call last):
 File "/global/common/cori/contrib/lsst/pserv/20161111/pserv/bin/load_db.py", line 104, in <module>
   dry_run=args.dry_run)
 File "/global/common/cori/contrib/lsst/pserv/20161111/pserv/bin/load_db.py", line 38, in ingest_forced_catalogs
   lambda c: [x[0] for x in c][0])
 File "/global/common/cori/contrib/lsst/pserv/20161111/pserv/python/desc/pserv/Pserv.py", line 91, in apply
   results = cursorFunc(cursor)
 File "/global/common/cori/contrib/lsst/pserv/20161111/pserv/bin/load_db.py", line 38, in <lambda>
   lambda c: [x[0] for x in c][0])
IndexError: list index out of range```

**Comment by jchiang87** [comment]
Worked for me:
```
[twinkles] ls -l Run3_40
lrwxrwxrwx 1 jchiang8 jchiang8 48 Nov 20 16:20 Run3_40 -> /global/cscratch1/sd/desc/twinkles/work/4/output/
[twinkles] load_db.py --dry_run Run3_40 "Twinkles Run3 test"
Ingest registry file /global/u1/j/jchiang8/twinkles/Run3_40/_parent/registry.sqlite3
Ingest calexp info
Ingest object catalog Run3_40/deepCoadd-results/merged/0/0,0/ref-0-0,0.fits
Processing band u for 0 visits.
Processing band g for 10 visits.
Processing v250-fg R2,2 S1,1
Processing v251-fg R2,2 S1,1
Processing v252-fg R2,2 S1,1
Processing v253-fg R2,2 S1,1
Processing v254-fg R2,2 S1,1
Processing v255-fg R2,2 S1,1
Processing v256-fg R2,2 S1,1
Processing v257-fg R2,2 S1,1
Processing v258-fg R2,2 S1,1
Processing v259-fg R2,2 S1,1
Processing band r for 20 visits.
Processing v230-fr R2,2 S1,1
Processing v231-fr R2,2 S1,1
Processing v232-fr R2,2 S1,1
Processing v233-fr R2,2 S1,1
Processing v234-fr R2,2 S1,1
Processing v235-fr R2,2 S1,1
Processing v236-fr R2,2 S1,1
Processing v237-fr R2,2 S1,1
Processing v238-fr R2,2 S1,1
Processing v239-fr R2,2 S1,1
Processing v240-fr R2,2 S1,1
Processing v241-fr R2,2 S1,1
Processing v242-fr R2,2 S1,1
Processing v243-fr R2,2 S1,1
Processing v244-fr R2,2 S1,1
Processing v245-fr R2,2 S1,1
Processing v246-fr R2,2 S1,1
Processing v247-fr R2,2 S1,1
Processing v248-fr R2,2 S1,1
Processing v249-fr R2,2 S1,1
Processing band i for 10 visits.
Processing v260-fi R2,2 S1,1
Processing v261-fi R2,2 S1,1
Processing v262-fi R2,2 S1,1
Processing v263-fi R2,2 S1,1
Processing v264-fi R2,2 S1,1
Processing v265-fi R2,2 S1,1
Processing v266-fi R2,2 S1,1
Processing v267-fi R2,2 S1,1
Processing v268-fi R2,2 S1,1
Processing v269-fi R2,2 S1,1
Processing band z for 1 visits.
Processing v280-fz R2,2 S1,1
Processing band y for 0 visits.
OrderedDict()
[twinkles] 
```

**Comment by heather999** [comment]
Perhaps the problem was that I was running from within a directory where I didn't have write permissions?  I've rerun it from within a directory I have write access and it worked. Or maybe it was a transient issue on Cori - we had more than a few of those that week. Closing issue..
